### create user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email" : "test@test.com",
  "password": "1234"
}

### signin user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email" : "test@test.com",
  "password": "1234"
}

### signout user
POST http://localhost:3000/auth/signout

### current user
Get http://localhost:3000/auth/whoami

### find user
Get http://localhost:3000/auth/2

### find user given email
Get http://localhost:3000/auth?email=

### delete user given id
Delete http://localhost:3000/auth/1

### Update user
Patch http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234",
  "admin": true
}